kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: demo2-cluster
  region: us-east-2
  version: "1.27"
nodeGroups:
  - name: demo2-ng
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      allow: true
