apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      type: nginx
  template:
    metadata:
      name: nginx
      labels:
        type: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
              hostPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  selector:
    type: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30007