apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    env: dev
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 8080