apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 5Gi
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  volumeName: task-pv-volume
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: Pod
metadata:
 name: webserver
 labels:
  app: api
spec:
  containers: 
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: task-pv-claim